/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/manager/bebidas`; params?: Router.UnknownInputParams; } | { pathname: `/manager/business`; params?: Router.UnknownInputParams; } | { pathname: `/manager/cajeros`; params?: Router.UnknownInputParams; } | { pathname: `/manager/corte-caja`; params?: Router.UnknownInputParams; } | { pathname: `/manager/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/manager/login`; params?: Router.UnknownInputParams; } | { pathname: `/manager/orders`; params?: Router.UnknownInputParams; } | { pathname: `/manager/products`; params?: Router.UnknownInputParams; } | { pathname: `/manager/reports`; params?: Router.UnknownInputParams; } | { pathname: `/pos`; params?: Router.UnknownInputParams; } | { pathname: `/pos/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/bebidas`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/business`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/cajeros`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/corte-caja`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/login`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/products`; params?: Router.UnknownOutputParams; } | { pathname: `/manager/reports`; params?: Router.UnknownOutputParams; } | { pathname: `/pos`; params?: Router.UnknownOutputParams; } | { pathname: `/pos/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/manager/bebidas${`?${string}` | `#${string}` | ''}` | `/manager/business${`?${string}` | `#${string}` | ''}` | `/manager/cajeros${`?${string}` | `#${string}` | ''}` | `/manager/corte-caja${`?${string}` | `#${string}` | ''}` | `/manager/dashboard${`?${string}` | `#${string}` | ''}` | `/manager/login${`?${string}` | `#${string}` | ''}` | `/manager/orders${`?${string}` | `#${string}` | ''}` | `/manager/products${`?${string}` | `#${string}` | ''}` | `/manager/reports${`?${string}` | `#${string}` | ''}` | `/pos${`?${string}` | `#${string}` | ''}` | `/pos/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/manager/bebidas`; params?: Router.UnknownInputParams; } | { pathname: `/manager/business`; params?: Router.UnknownInputParams; } | { pathname: `/manager/cajeros`; params?: Router.UnknownInputParams; } | { pathname: `/manager/corte-caja`; params?: Router.UnknownInputParams; } | { pathname: `/manager/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/manager/login`; params?: Router.UnknownInputParams; } | { pathname: `/manager/orders`; params?: Router.UnknownInputParams; } | { pathname: `/manager/products`; params?: Router.UnknownInputParams; } | { pathname: `/manager/reports`; params?: Router.UnknownInputParams; } | { pathname: `/pos`; params?: Router.UnknownInputParams; } | { pathname: `/pos/login`; params?: Router.UnknownInputParams; };
    }
  }
}
